Initial universal libs support

diff --git a/SourcesAndScripts/Scripts/boost_build b/SourcesAndScripts/Scripts/boost_build
--- a/SourcesAndScripts/Scripts/boost_build
+++ b/SourcesAndScripts/Scripts/boost_build
@@ -6,9 +6,9 @@
 
 set -e
 
-BOOST_VERSION_1="1.74.0"
-BOOST_VERSION_2="1_74_0"
-SHA256="afff36d392885120bcac079148c177d1f6f7730ec3d47233aa51b0afa4db94a5"
+BOOST_VERSION_1="1.75.0"
+BOOST_VERSION_2="1_75_0"
+SHA256="aeb26f80e80945e82ee93e5939baebdca47b9dee80a07d3144be1e1a6a66dd6a"
 
 starttimestamp=$(date +%s)
 
@@ -24,24 +24,49 @@ source "${MY_PATH}/env"
 source "${MY_PATH}/functions"
 
 check_wget
-check_xcode
+
+if ! [ is_apple_silicon_mac ]; then
+  echo "Error: Boost requires Apple Silicon mac to build universal libs" >&2
+  exit 1
+fi
 
 cd "${SOURCES_PATH}"
 rm -rf "boost"*
 get_src_and_verify_checksum "boost_${BOOST_VERSION_2}.tar.gz" "${SHA256}" "https://dl.bintray.com/boostorg/release/${BOOST_VERSION_1}/source/boost_${BOOST_VERSION_2}.tar.gz"
 tar xf "${SOURCES_PATH}/archives/boost_${BOOST_VERSION_2}.tar.gz" -C .
+cp -R "boost_${BOOST_VERSION_2}" "boost_${BOOST_VERSION_2}-arm64"
 ln -s "boost_${BOOST_VERSION_2}" "boost"
 cd "boost"
+# Build x86_64
 rm -rf "stage"
-./bootstrap.sh --with-libraries=chrono,filesystem,iostreams,locale,program_options,random,regex,system,timer,test,thread --with-toolset=clang
-./b2 threading=multi --layout=tagged link=shared variant=release -sNO_LZMA=1 -sNO_ZSTD=1 cxxstd=14
+source "${MY_PATH}/env"
+arch -x86_64 ./bootstrap.sh --with-libraries=chrono,context,coroutine,filesystem,iostreams,locale,program_options,random,regex,system,timer,test,thread abi=sysv address-model=64 architecture=x86 binary-format=mach-o threading=multi toolset=clang
+#./bootstrap.sh --with-libraries=chrono,context,coroutine,filesystem,iostreams,locale,program_options,random,regex,system,timer,test,thread abi=sysv address-model=64 architecture=x86 binary-format=mach-o threading=multi toolset=clang
+export LDFLAGS="${LDFLAGS_X86_64}"
+export CFLAGS="${CFLAGS_X86_64}"
+export CXXFLAGS="${CXXFLAGS_X86_64}"
+arch -x86_64 ./b2 -q cxxflags="${CXXFLAGS}" linkflags="${LDFLAGS}" --layout=tagged-1.66 link=shared variant=release -sNO_LZMA=1 -sNO_ZSTD=1 cxxstd=14 abi=sysv address-model=64 architecture=x86 binary-format=mach-o threading=multi toolset=clang
+#./b2 -q cxxflags="${CXXFLAGS}" linkflags="${LDFLAGS}" --layout=tagged-1.66 link=shared variant=release -sNO_LZMA=1 -sNO_ZSTD=1 cxxstd=14 abi=sysv address-model=64 architecture=x86 binary-format=mach-o threading=multi toolset=clang
+# Build arm64
+cd "${SOURCES_PATH}/boost_${BOOST_VERSION_2}-arm64"
+rm -rf "stage"
+patch -b -p0 < "${SCRIPTS_PATH}/boost.patch"
+source "${MY_PATH}/env"
+arch -arm64 ./bootstrap.sh --with-libraries=chrono,context,coroutine,filesystem,iostreams,locale,program_options,random,regex,system,timer,test,thread abi=aapcs address-model=64 architecture=arm binary-format=mach-o threading=multi toolset=clang
+#./bootstrap.sh --with-libraries=chrono,context,coroutine,filesystem,iostreams,locale,program_options,random,regex,system,timer,test,thread abi=aapcs address-model=64 architecture=arm binary-format=mach-o threading=multi toolset=clang
+export LDFLAGS="${LDFLAGS_ARM64}"
+export CFLAGS="${CFLAGS_ARM64}"
+export CXXFLAGS="${CXXFLAGS_ARM64}"
+arch -arm64 ./b2 -q cxxflags="${CXXFLAGS}" linkflags="${LDFLAGS}" --layout=tagged-1.66 link=shared variant=release -sNO_LZMA=1 -sNO_ZSTD=1 cxxstd=14 abi=aapcs address-model=64 architecture=arm binary-format=mach-o threading=multi toolset=clang
+#./b2 -q cxxflags="${CXXFLAGS}" linkflags="${LDFLAGS}" --layout=tagged-1.66 link=shared variant=release -sNO_LZMA=1 -sNO_ZSTD=1 cxxstd=14 abi=aapcs address-model=64 architecture=arm binary-format=mach-o threading=multi toolset=clang
 cd "stage/lib"
 mkdir "boost_${BOOST_VERSION_2}-RELEASE"
-cp *".dylib" "boost_${BOOST_VERSION_2}-RELEASE"
+for filename in *.dylib ; do
+  lipo -create "${SOURCES_PATH}/boost_${BOOST_VERSION_2}-arm64/stage/lib/${filename}" "${SOURCES_PATH}/boost_${BOOST_VERSION_2}/stage/lib/${filename}" -output "boost_${BOOST_VERSION_2}-RELEASE/${filename}"
+done
 cd "boost_${BOOST_VERSION_2}-RELEASE"
 for filename in * ; do
   install_name_tool -id "@rpath/${filename}" "${filename}"
-  edit_dylib_deps "${filename}"
 done
 rm -rf "${LIBS_PATH}/libboost"*
 cp -rf * "${LIBS_PATH}/"
diff --git a/SourcesAndScripts/Scripts/functions b/SourcesAndScripts/Scripts/functions
--- a/SourcesAndScripts/Scripts/functions
+++ b/SourcesAndScripts/Scripts/functions
@@ -13,115 +13,93 @@ check_wget() {
   fi
 }
 
-check_xcode() {
-  if xcode-select --install 2>&1 | grep installed; then
-    echo "==> Xcode Command Line Tools are installed..."
-  else
-    echo "==> Xcode Command Line Tools aren't installed, installing..."
-    xcode-select --install
-  fi
-}
-
-# TODO: use pixman from MacCompileStuff
 check_pixman() {
-  if [ ! -f "/usr/local/lib/libpixman-1.0.dylib" ]; then
-    echo 'Error: pixman is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
+  if ! [ -f "${LIBS_PATH}/libpixman-1.0.dylib" ]; then
+    echo 'Error: pixman is not prepared. You must build all libraries in defined order.' >&2
     exit 1
   fi
 }
 
-# TODO: use fontconfig from MacCompileStuff
 check_fontconfig() {
-  if ! [ -x "$(command -v fc-cache)" ]; then
-    echo 'Error: fontconfig is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
+  if ! [ -f "${LIBS_PATH}/libfontconfig.dylib" ]; then
+    echo 'Error: fontconfig is not prepared. You must build all libraries in defined order.' >&2
     exit 1
   fi
 }
 
-# TODO: use freetype from MacCompileStuff
 check_freetype() {
-  if ! [ -x "$(command -v freetype-config)" ]; then
-    echo 'Error: freetype is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
+  if ! [ -f "${LIBS_PATH}/libfreetype.dylib" ]; then
+    echo 'Error: freetype is not prepared. You must build all libraries in defined order.' >&2
     exit 1
   fi
 }
 
-# TODO: use libpng from MacCompileStuff
 check_libpng() {
-  if ! [ -x "$(command -v libpng-config)" ]; then
-    echo 'Error: libpng is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
+  if ! [ -f "${LIBS_PATH}/libpng.dylib" ]; then
+    echo 'Error: libpng is not prepared. You must build all libraries in defined order.' >&2
     exit 1
   fi
 }
 
-# TODO: use libffi from MacCompileStuff
 check_libffi() {
-  if [ ! -f "/usr/local/Cellar/libffi/"*"/lib/libffi.dylib" ]; then
+  if ! [ -f "${LIBS_PATH}/libffi.dylib" ]; then
     echo 'Error: libffi is not installed or is not linked. Use Homebrew, install it and force link it. See https://brew.sh/' >&2
     exit 1
   fi
 }
 
-# TODO: use glib from MacCompileStuff
 check_glib() {
-  if ! [ -x "$(command -v gobject-query)" ]; then
-    echo 'Error: glib is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
+  if ! [ -f "${LIBS_PATH}/libglib-2.0.0.dylib" ]; then
+    echo 'Error: glib is not prepared. You must build all libraries in defined order.' >&2
     exit 1
   fi
 }
 
-# TODO: use gettext from MacCompileStuff
 check_gettext() {
-  if ! [ -x "$(command -v gettext)" ]; then
-    echo 'Error: gettext is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
+  if ! [ -f "${LIBS_PATH}/libintl.dylib" ]; then
+    echo 'Error: gettext is not prepared. You must build all libraries in defined order.' >&2
     exit 1
   fi
 }
 
-# TODO: use graphite2 from MacCompileStuff
 check_graphite2() {
-  if ! [ -x "$(command -v gr2fonttest)" ]; then
-    echo 'Error: graphite2 is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
+  if ! [ -f "${LIBS_PATH}/libgraphite2.dylib" ]; then
+    echo 'Error: graphite2 is not prepared. You must build all libraries in defined order.' >&2
     exit 1
   fi
 }
 
-# TODO: use cairo from MacCompileStuff
 check_cairo() {
-  if ! [ -x "$(command -v cairo-sphinx)" ]; then
-    echo 'Error: cairo is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
+  if ! [ -f "${LIBS_PATH}/libcairo.dylib" ]; then
+    echo 'Error: cairo is not prepared. You must build all libraries in defined order.' >&2
     exit 1
   fi
 }
 
-# TODO: use harfbuzz from MacCompileStuff
 check_harfbuzz() {
-  if ! [ -x "$(command -v hb-view)" ]; then
-    echo 'Error: harfbuzz is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
+  if ! [ -f "${LIBS_PATH}/libharfbuzz.dylib" ]; then
+    echo 'Error: harfbuzz is not prepared. You must build all libraries in defined order.' >&2
     exit 1
   fi
 }
 
-# TODO: use fribidi from MacCompileStuff
 check_fribidi() {
-  if [ ! -f "/usr/local/opt/fribidi/lib/libfribidi.0.dylib" ]; then
-    echo 'Error: fribidi is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
+  if ! [ -f "${LIBS_PATH}/libfribidi.dylib" ]; then
+    echo 'Error: fribidi is not prepared. You must build all libraries in defined order.' >&2
     exit 1
   fi
 }
 
-# TODO: use libogg from MacCompileStuff
 check_libogg() {
-  if [ ! -f "/usr/local/opt/libogg/lib/libogg.0.dylib" ]; then
-    echo 'Error: libogg is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
+  if ! [ -f "${LIBS_PATH}/libogg.dylib" ]; then
+    echo 'Error: libogg is not prepared. You must build all libraries in defined order.' >&2
     exit 1
   fi
 }
 
-# TODO: use pcre from MacCompileStuff
 check_pcre() {
-  if [ ! -f "/usr/local/opt/pcre/lib/libpcre.1.dylib" ]; then
-    echo 'Error: pcre is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
+  if ! [ -f "${LIBS_PATH}/libpcre.dylib" ]; then
+    echo 'Error: pcre is not prepared. You must build all libraries in defined order.' >&2
     exit 1
   fi
 }
@@ -158,25 +136,6 @@ remove_rpath_if_exists() {
   fi
 }
 
-edit_dylib_deps() {
-  DYLIB=$1
-  DYLIB_DEPS=$(otool -L ${DYLIB} | awk '{print $1;}' | tail -n +2)
-  MCS_DYLIBS_PATH="${MY_PATH}/../../lib"
-
-  for DEP in ${DYLIB_DEPS}; do
-    DEP_BASE=$(basename ${DEP})
-    if [ "${DEP_BASE}" == "$(basename ${DYLIB})" ]; then
-      continue
-    fi
-    # Is this our redistributable file?
-    if [ -f $(dirname ${DYLIB})/${DEP_BASE} ]; then
-      install_name_tool -change "${DEP}" "@loader_path/${DEP_BASE}" ${DYLIB}
-    elif [ -f "${MCS_DYLIBS_PATH}/${DEP_BASE}" ]; then
-      install_name_tool -change "${DEP}" "@loader_path/${DEP_BASE}" ${DYLIB}
-    fi
-  done
-}
-
 get_src_and_verify_checksum() {
   NAME=$1
   SHA256=$2
@@ -203,6 +162,33 @@ get_src_and_verify_checksum() {
     echo "==> SHA256 = ${SHA256}" >&2
     echo "==> actual = ${SHA256_TO_VERIFY}" >&2
     exit 1
+  fi
+}
+
+generate_pkgconfig_file() {
+  NAME=$1
+  VERSION=$2
+
+  if ! [ -f "${PKG_CONFIG_PATH}/${NAME}.pc.template" ]; then
+    echo "Error: pkgconfig template for ${NAME} doesn't exist" >&2
+    exit 1
+  fi
+
+  rm -rf "${PKG_CONFIG_PATH}/${NAME}.pc"
+  cp "${PKG_CONFIG_PATH}/${NAME}.pc.template" "${PKG_CONFIG_PATH}/${NAME}.pc"
+  sed -i '' "s:prefix=PATH:prefix=${ROOT_PATH}:" "${PKG_CONFIG_PATH}/${NAME}.pc"
+  sed -i '' "s/Version: VERSION/Version: ${VERSION}/" "${PKG_CONFIG_PATH}/${NAME}.pc"
+}
+
+is_apple_silicon_mac() {
+  if [ "$(uname -s)" = Darwin ]; then
+    if [[ "$(/usr/sbin/sysctl -n machdep.cpu.brand_string)" == *"Apple"* ]]; then
+      true
+    else
+      false
+    fi
+  else
+    false
   fi
 }
 
diff --git a/SourcesAndScripts/Scripts/glib_build b/SourcesAndScripts/Scripts/glib_build
--- a/SourcesAndScripts/Scripts/glib_build
+++ b/SourcesAndScripts/Scripts/glib_build
@@ -6,9 +6,9 @@
 
 set -e
 
-GLIB_VERSION="2.66.3"
+GLIB_VERSION="2.66.4"
 GLIB_VERSION_SHORT="2.66"
-SHA256="79f31365a99cb1cc9db028625635d1438890702acde9e2802eae0acebcf7b5b1"
+SHA256="97df8670e32f9fd4f7392b0980e661dd625012015d58350da1e58e343f4af984"
 
 starttimestamp=$(date +%s)
 
@@ -22,52 +22,86 @@ fi
 
 source "${MY_PATH}/env"
 source "${MY_PATH}/functions"
-unset MACOSX_DEPLOYMENT_TARGET
 
 check_wget
-check_xcode
 check_meson
 check_ninja
 check_pcre
 check_libffi
 check_gettext
 
+if ! [ is_apple_silicon_mac ]; then
+  echo "Error: Boost requires Apple Silicon mac to build universal libs" >&2
+  exit 1
+fi
+
 cd "${SOURCES_PATH}"
 rm -rf "glib"*
 get_src_and_verify_checksum "glib-${GLIB_VERSION}.tar.xz" "${SHA256}" "https://download.gnome.org/sources/glib/${GLIB_VERSION_SHORT}/glib-${GLIB_VERSION}.tar.xz"
 tar xf "${SOURCES_PATH}/archives/glib-${GLIB_VERSION}.tar.xz" -C .
+cp -R "glib-${GLIB_VERSION}" "glib-${GLIB_VERSION}-arm64"
 ln -s "glib-${GLIB_VERSION}" "glib"
 cd "glib"
-mkdir "build"
-meson -Dbsymbolic_functions=false -Ddtrace=false -Diconv=auto --default-library=shared --buildtype=release . "build"
-cd "build"
-ninja
+# Build x86_64
+source "${MY_PATH}/env"
+unset MACOSX_DEPLOYMENT_TARGET
+export LDFLAGS="${LDFLAGS_X86_64}"
+export CFLAGS="${CFLAGS_X86_64}"
+export CXXFLAGS="${CXXFLAGS_X86_64}"
+mkdir -p "build/glib"
+#meson -Dbsymbolic_functions=false -Ddtrace=false -Diconv=auto --default-library=shared --buildtype=release --cross-file="${SCRIPTS_PATH}/cross_file_x86_64.txt" . "build"
+arch -x86_64 /opt/homebrew_x86_64/bin/meson -Dbsymbolic_functions=false -Ddtrace=false -Diconv=auto --default-library=shared --buildtype=release . "build"
+cd "build/glib"
+ln -s "${LIBS_PATH}/libpcre.1.dylib"
+ln -s "${LIBS_PATH}/libintl.8.dylib"
+cd ..
+arch -x86_64 /opt/homebrew_x86_64/bin/ninja
+# Build arm64
+cd "${SOURCES_PATH}/glib-${GLIB_VERSION}-arm64"
+source "${MY_PATH}/env"
+unset MACOSX_DEPLOYMENT_TARGET
+export LDFLAGS="${LDFLAGS_ARM64}"
+export CFLAGS="${CFLAGS_ARM64}"
+export CXXFLAGS="${CXXFLAGS_ARM64}"
+mkdir -p "build/glib"
+#meson -Dbsymbolic_functions=false -Ddtrace=false -Diconv=auto --default-library=shared --buildtype=release --cross-file="${SCRIPTS_PATH}/cross_file_arm64.txt" . "build"
+arch -arm64 /opt/homebrew/bin/meson -Dbsymbolic_functions=false -Ddtrace=false -Diconv=auto --default-library=shared --buildtype=release . "build"
+cd "build/glib"
+ln -s "${LIBS_PATH}/libpcre.1.dylib"
+ln -s "${LIBS_PATH}/libintl.8.dylib"
+cd ..
+arch -arm64 /opt/homebrew/bin/ninja
 mkdir "glib-${GLIB_VERSION}-RELEASE"
-cp "glib/libglib-2.0.0.dylib" "glib-${GLIB_VERSION}-RELEASE/libglib-2.0.0.dylib"
-cp "gmodule/libgmodule-2.0.0.dylib" "glib-${GLIB_VERSION}-RELEASE/libgmodule-2.0.0.dylib"
-cp "gobject/libgobject-2.0.0.dylib" "glib-${GLIB_VERSION}-RELEASE/libgobject-2.0.0.dylib"
-cp "gthread/libgthread-2.0.0.dylib" "glib-${GLIB_VERSION}-RELEASE/libgthread-2.0.0.dylib"
-cp "gio/libgio-2.0.0.dylib" "glib-${GLIB_VERSION}-RELEASE/libgio-2.0.0.dylib"
 cd "glib-${GLIB_VERSION}-RELEASE"
-# TODO: Use MCS' pcre, libffi and gettext
+lipo -create "${SOURCES_PATH}/glib-${GLIB_VERSION}-arm64/build/glib/libglib-2.0.0.dylib" "${SOURCES_PATH}/glib-${GLIB_VERSION}/build/glib/libglib-2.0.0.dylib" -output "libglib-2.0.0.dylib"
+lipo -create "${SOURCES_PATH}/glib-${GLIB_VERSION}-arm64/build/gmodule/libgmodule-2.0.0.dylib" "${SOURCES_PATH}/glib-${GLIB_VERSION}/build/gmodule/libgmodule-2.0.0.dylib" -output "libgmodule-2.0.0.dylib"
+lipo -create "${SOURCES_PATH}/glib-${GLIB_VERSION}-arm64/build/gobject/libgobject-2.0.0.dylib" "${SOURCES_PATH}/glib-${GLIB_VERSION}/build/gobject/libgobject-2.0.0.dylib" -output "libgobject-2.0.0.dylib"
+lipo -create "${SOURCES_PATH}/glib-${GLIB_VERSION}-arm64/build/gthread/libgthread-2.0.0.dylib" "${SOURCES_PATH}/glib-${GLIB_VERSION}/build/gthread/libgthread-2.0.0.dylib" -output "libgthread-2.0.0.dylib"
+lipo -create "${SOURCES_PATH}/glib-${GLIB_VERSION}-arm64/build/gio/libgio-2.0.0.dylib" "${SOURCES_PATH}/glib-${GLIB_VERSION}/build/gio/libgio-2.0.0.dylib" -output "libgio-2.0.0.dylib"
 for filename in * ; do
   install_name_tool -id "@rpath/${filename}" "${filename}"
-  edit_dylib_deps "${filename}"
-  remove_rpath_if_exists "${filename}" "@loader_path/../glib"
+    remove_rpath_if_exists "${filename}" "@loader_path/../glib"
   remove_rpath_if_exists "${filename}" "@loader_path/../gmodule"
   remove_rpath_if_exists "${filename}" "@loader_path/../gobject"
-  remove_rpath_if_exists "${filename}" "/usr/local/Cellar/pcre/"
-  remove_rpath_if_exists "${filename}" "/usr/local/Cellar/libffi/"
+  remove_rpath_if_exists "${filename}" "${LIBS_PATH}"
 done
-rm -rf "${LIBS_PATH}/libglib-2.0.0.dylib" "${LIBS_PATH}/libgmodule-2.0.0.dylib" "${LIBS_PATH}/libgobject-2.0.0.dylib" "${LIBS_PATH}/libgthread-2.0.0.dylib"
+rm -rf "${LIBS_PATH}/libglib-2.0.0.dylib" "${LIBS_PATH}/libgmodule-2.0.0.dylib" "${LIBS_PATH}/libgobject-2.0.0.dylib" "${LIBS_PATH}/libgthread-2.0.0.dylib" "${LIBS_PATH}/libgio-2.0.0.dylib" "${LIBS_PATH}/libglib-2.0.dylib" "${LIBS_PATH}/libgmodule-2.0.dylib" "${LIBS_PATH}/libgobject-2.0.dylib" "${LIBS_PATH}/libgthread-2.0.dylib" "${LIBS_PATH}/libgio-2.0.dylib"
 cp -rf * "${LIBS_PATH}/"
+ln -s "libglib-2.0.0.dylib" "${LIBS_PATH}/libglib-2.0.dylib"
+ln -s "libgmodule-2.0.0.dylib" "${LIBS_PATH}/libgmodule-2.0.dylib"
+ln -s "libgobject-2.0.0.dylib" "${LIBS_PATH}/libgobject-2.0.dylib"
+ln -s "libgthread-2.0.0.dylib" "${LIBS_PATH}/libgthread-2.0.dylib"
+ln -s "libgio-2.0.0.dylib" "${LIBS_PATH}/libgio-2.0.dylib"
 rm -rf "${HEADERS_PATH}/glib"*
 mkdir -p "${HEADERS_PATH}/glib-2.0/gio"
 mkdir -p "${HEADERS_PATH}/glib-2.0/glib/deprecated"
 mkdir -p "${HEADERS_PATH}/glib-2.0/gobject"
 # TODO: Use glib-public-headers.txt and etc for Headers
-cp "${SOURCES_PATH}/glib/build/glib/glibconfig.h" "${HEADERS_PATH}/"
+cp "${SOURCES_PATH}/glib/build/glib/glibconfig.h" "${HEADERS_PATH}/glibconfig_x86_64.h"
+cp "${SOURCES_PATH}/glib-${GLIB_VERSION}-arm64/build/glib/glibconfig.h" "${HEADERS_PATH}/glibconfig_arm64.h"
+printf "#ifdef __x86_64__\n#include \"glibconfig_x86_64.h\"\n#else\n#include \"glibconfig_arm64.h\"\n#endif\n" > "${HEADERS_PATH}/glibconfig.h"
 cp "${SOURCES_PATH}/glib/build/gobject/glib-enumtypes.h" "${HEADERS_PATH}/glib-2.0/gobject/glib-enumtypes.h"
+cp "${SOURCES_PATH}/glib/build/gio/gioenumtypes.h" "${HEADERS_PATH}/glib-2.0/gio/gioenumtypes.h"
 cd "${SOURCES_PATH}/glib/glib"
 cp "glib-object.h" "glib-unix.h" "glib.h" "${HEADERS_PATH}/glib-2.0/"
 cp "${SOURCES_PATH}/glib/glib/"*.h "${HEADERS_PATH}/glib-2.0/glib/"
@@ -75,6 +109,8 @@ cp "${SOURCES_PATH}/glib/glib/deprecated/"*.h "${HEADERS_PATH}/glib-2.0/glib/dep
 cp "${SOURCES_PATH}/glib/gio/"*.h "${HEADERS_PATH}/glib-2.0/gio/"
 cp "${SOURCES_PATH}/glib/gmodule/gmodule.h" "${HEADERS_PATH}/glib-2.0/"
 cp "${SOURCES_PATH}/glib/gobject/"*.h "${HEADERS_PATH}/glib-2.0/gobject/"
+generate_pkgconfig_file "glib-2.0" "${GLIB_VERSION}"
+generate_pkgconfig_file "gio-2.0" "${GLIB_VERSION}"
 echo "==> DONE ..."
 echo
 time_interval_to_string "${starttimestamp}" "$(date +%s)"
diff --git a/SourcesAndScripts/Scripts/harfbuzz_build b/SourcesAndScripts/Scripts/harfbuzz_build
--- a/SourcesAndScripts/Scripts/harfbuzz_build
+++ b/SourcesAndScripts/Scripts/harfbuzz_build
@@ -24,7 +24,6 @@ source "${MY_PATH}/functions"
 unset MACOSX_DEPLOYMENT_TARGET
 
 check_wget
-check_xcode
 check_meson
 check_ninja
 check_libffi
@@ -33,30 +32,53 @@ check_gettext
 check_freetype
 check_graphite2
 
+if ! [ is_apple_silicon_mac ]; then
+  echo "Error: Boost requires Apple Silicon mac to build universal libs" >&2
+  exit 1
+fi
+
 cd "${SOURCES_PATH}"
 rm -rf "harfbuzz"*
 get_src_and_verify_checksum "harfbuzz-${HARFBUZZ_VERSION}.tar.xz" "${SHA256}" "https://github.com/harfbuzz/harfbuzz/releases/download/${HARFBUZZ_VERSION}/harfbuzz-${HARFBUZZ_VERSION}.tar.xz"
 tar xf "${SOURCES_PATH}/archives/harfbuzz-${HARFBUZZ_VERSION}.tar.xz" -C .
+cp -R "harfbuzz-${HARFBUZZ_VERSION}" "harfbuzz-${HARFBUZZ_VERSION}-arm64"
 ln -s "harfbuzz-${HARFBUZZ_VERSION}" "harfbuzz"
 cd "harfbuzz"
+# Build x86_64
+source "${MY_PATH}/env"
+unset MACOSX_DEPLOYMENT_TARGET
+export LDFLAGS="${LDFLAGS_X86_64}"
+export CFLAGS="${CFLAGS_X86_64}"
+export CXXFLAGS="${CXXFLAGS_X86_64}"
 mkdir "build"
-meson -Dgraphite=enabled -Dcoretext=enabled --buildtype=release --default-library=shared . "build"
+#meson -Dgraphite=enabled -Dcoretext=enabled --buildtype=release --default-library=shared --cross-file="${SCRIPTS_PATH}/cross_file_x86_64.txt" . "build"
+arch -x86_64 /opt/homebrew_x86_64/bin/meson -Dgraphite=enabled -Dcoretext=enabled -Dintrospection=disabled --buildtype=release --default-library=shared . "build"
 cd "build"
-ninja
+arch -x86_64 /opt/homebrew_x86_64/bin/ninja
+# Build arm64
+cd "${SOURCES_PATH}/harfbuzz-${HARFBUZZ_VERSION}-arm64"
+source "${MY_PATH}/env"
+unset MACOSX_DEPLOYMENT_TARGET
+export LDFLAGS="${LDFLAGS_ARM64}"
+export CFLAGS="${CFLAGS_ARM64}"
+export CXXFLAGS="${CXXFLAGS_ARM64}"
+mkdir "build"
+#meson -Dgraphite=enabled -Dcoretext=enabled --buildtype=release --default-library=shared --cross-file="${SCRIPTS_PATH}/cross_file_arm64.txt" . "build"
+arch -arm64 /opt/homebrew/bin/meson -Dgraphite=enabled -Dcoretext=enabled -Dintrospection=disabled --buildtype=release --default-library=shared . "build"
+cd "build"
+arch -arm64 /opt/homebrew/bin/ninja
 mkdir "harfbuzz-${HARFBUZZ_VERSION}-RELEASE"
-cp "src/libharfbuzz.0.dylib" "harfbuzz-${HARFBUZZ_VERSION}-RELEASE/libharfbuzz.0.dylib"
 cd "harfbuzz-${HARFBUZZ_VERSION}-RELEASE"
+lipo -create "${SOURCES_PATH}/harfbuzz-${HARFBUZZ_VERSION}-arm64/build/src/libharfbuzz.0.dylib" "${SOURCES_PATH}/harfbuzz-${HARFBUZZ_VERSION}/build/src/libharfbuzz.0.dylib" -output "libharfbuzz.0.dylib"
 install_name_tool -id "@rpath/libharfbuzz.0.dylib" "libharfbuzz.0.dylib"
-edit_dylib_deps "libharfbuzz.0.dylib"
-remove_rpath_if_exists "libharfbuzz.0.dylib" "/usr/local/opt/freetype/lib"
-remove_rpath_if_exists "libharfbuzz.0.dylib" "/usr/local/Cellar/graphite2/"
+remove_rpath_if_exists "libharfbuzz.0.dylib" "${LIBS_PATH}"
 rm -rf "${LIBS_PATH}/libharfbuzz.0.dylib" "${LIBS_PATH}/libharfbuzz.dylib"
 cp -rf "libharfbuzz.0.dylib" "${LIBS_PATH}/libharfbuzz.0.dylib"
 ln -s "libharfbuzz.0.dylib" "${LIBS_PATH}/libharfbuzz.dylib"
 rm -rf "${HEADERS_PATH}/harfbuzz"
 mkdir "${HEADERS_PATH}/harfbuzz"
-cd "${SOURCES_PATH}/harfbuzz/src"
-cp "hb-blob.h" "hb-buffer.h" "hb-common.h" "hb-deprecated.h" "hb-draw.h" "hb-face.h" "hb-font.h" "hb-map.h" "hb-set.h" "hb-shape-plan.h" "hb-shape.h" "hb-style.h" "hb-unicode.h" "hb-version.h" "hb.h" "${HEADERS_PATH}/harfbuzz/"
+cp "${SOURCES_PATH}/harfbuzz/src/"*".h" "${HEADERS_PATH}/harfbuzz/"
+generate_pkgconfig_file "harfbuzz" "${HARFBUZZ_VERSION}"
 echo "==> DONE ..."
 echo
 time_interval_to_string "${starttimestamp}" "$(date +%s)"
diff --git a/SourcesAndScripts/Scripts/pango_build b/SourcesAndScripts/Scripts/pango_build
--- a/SourcesAndScripts/Scripts/pango_build
+++ b/SourcesAndScripts/Scripts/pango_build
@@ -25,7 +25,6 @@ source "${MY_PATH}/functions"
 unset MACOSX_DEPLOYMENT_TARGET
 
 check_wget
-check_xcode
 check_libffi
 check_glib
 check_cairo
@@ -37,30 +36,50 @@ check_fribidi
 check_meson
 check_ninja
 
+if ! [ is_apple_silicon_mac ]; then
+  echo "Error: Boost requires Apple Silicon mac to build universal libs" >&2
+  exit 1
+fi
+
 cd "${SOURCES_PATH}"
 rm -rf "pango"*
 get_src_and_verify_checksum "pango-${PANGO_VERSION}.tar.xz" "${SHA256}" "http://ftp.gnome.org/pub/GNOME/sources/pango/${PANGO_VERSION_SHORT}/pango-${PANGO_VERSION}.tar.xz"
 tar xf "${SOURCES_PATH}/archives/pango-${PANGO_VERSION}.tar.xz" -C .
+cp -R "pango-${PANGO_VERSION}" "pango-${PANGO_VERSION}-arm64"
 ln -s "pango-${PANGO_VERSION}" "pango"
 cd "pango"
+# Build x86_64
+source "${MY_PATH}/env"
+unset MACOSX_DEPLOYMENT_TARGET
+export LDFLAGS="${LDFLAGS_X86_64}"
+export CFLAGS="${CFLAGS_X86_64}"
+export CXXFLAGS="${CXXFLAGS_X86_64}"
 mkdir "build"
 sed -i -e "/Werror=implicit-fallthrough/d" "meson.build"
-meson -Dintrospection=enabled -Duse_fontconfig=enabled --default-library=shared --buildtype=release . "build"
+arch -x86_64 /opt/homebrew_x86_64/bin/meson -Dintrospection=disabled -Duse_fontconfig=enabled --default-library=shared --buildtype=release . "build"
 cd "build"
-ninja
+arch -x86_64 /opt/homebrew_x86_64/bin/ninja
+# Build arm64
+cd "${SOURCES_PATH}/pango-${PANGO_VERSION}-arm64"
+source "${MY_PATH}/env"
+unset MACOSX_DEPLOYMENT_TARGET
+export LDFLAGS="${LDFLAGS_ARM64}"
+export CFLAGS="${CFLAGS_ARM64}"
+export CXXFLAGS="${CXXFLAGS_ARM64}"
+mkdir "build"
+sed -i -e "/Werror=implicit-fallthrough/d" "meson.build"
+arch -arm64 /opt/homebrew/bin/meson -Dintrospection=disabled -Duse_fontconfig=enabled --default-library=shared --buildtype=release . "build"
+cd "build"
+arch -arm64 /opt/homebrew/bin/ninja
 mkdir "pango-${PANGO_VERSION}-RELEASE"
-cp "pango/libpango-1.0.0.dylib" "pango-${PANGO_VERSION}-RELEASE/libpango-1.0.0.dylib"
-cp "pango/libpangocairo-1.0.0.dylib" "pango-${PANGO_VERSION}-RELEASE/libpangocairo-1.0.0.dylib"
-cp "pango/libpangoft2-1.0.0.dylib" "pango-${PANGO_VERSION}-RELEASE/libpangoft2-1.0.0.dylib"
 cd "pango-${PANGO_VERSION}-RELEASE"
+lipo -create "${SOURCES_PATH}/pango-${PANGO_VERSION}-arm64/build/pango/libpango-1.0.0.dylib" "${SOURCES_PATH}/pango-${PANGO_VERSION}/build/pango/libpango-1.0.0.dylib" -output "libpango-1.0.0.dylib"
+lipo -create "${SOURCES_PATH}/pango-${PANGO_VERSION}-arm64/build/pango/libpangocairo-1.0.0.dylib" "${SOURCES_PATH}/pango-${PANGO_VERSION}/build/pango/libpangocairo-1.0.0.dylib" -output "libpangocairo-1.0.0.dylib"
+lipo -create "${SOURCES_PATH}/pango-${PANGO_VERSION}-arm64/build/pango/libpangoft2-1.0.0.dylib" "${SOURCES_PATH}/pango-${PANGO_VERSION}/build/pango/libpangoft2-1.0.0.dylib" -output "libpangoft2-1.0.0.dylib"
 for filename in * ; do
   install_name_tool -id "@rpath/${filename}" "${filename}"
-  edit_dylib_deps "${filename}"
-  remove_rpath_if_exists "${filename}" "/usr/local/Cellar/cairo/"
-  remove_rpath_if_exists "${filename}" "/usr/local/opt/freetype/lib"
-  remove_rpath_if_exists "${filename}" "/usr/local/Cellar/harfbuzz/"
-  remove_rpath_if_exists "${filename}" "/usr/local/Cellar/fribidi/"
-  remove_rpath_if_exists "${filename}" "@loader_path/"
+    remove_rpath_if_exists "${filename}" "@loader_path/"
+  remove_rpath_if_exists "${filename}" "${LIBS_PATH}"
 done
 rm -rf "${LIBS_PATH}/libpango"*
 cp -rf * "${LIBS_PATH}/"
