Freetype 2.10.2 and new scripts usage

diff --git a/SourcesAndScripts/Scripts/freetype_build b/SourcesAndScripts/Scripts/freetype_build
--- a/SourcesAndScripts/Scripts/freetype_build
+++ b/SourcesAndScripts/Scripts/freetype_build
@@ -1,107 +1,50 @@
 #!/usr/bin/env bash
 #
 # freetype_build
-# Martin Hrubý (hrubymar10), 2018-2019
+# Martin Hrubý (hrubymar10), 2018-2020
 #
 
-FREETYPE_VERSION="2.10.1"
+set -e
 
-edit_dylib_deps() {
-        DYLIB=$1
-        DEPS=$(otool -L ${DYLIB} | awk '{print $1;}' | tail -n +2)
-
-        for DEP in $DEPS; do
-                DEP_BASE=$(basename ${DEP})
-                if [ "$DEP_BASE" == "$(basename $DYLIB)" ]; then
-                        continue
-                fi
-                # Is this our redistributable file?
-                if [ -f $(dirname ${DYLIB})/${DEP_BASE} ]; then
-                        install_name_tool -change "${DEP}" "@loader_path/${DEP_BASE}" ${DYLIB}
-                fi
-        done
-}
-
-time_interval_to_string() {
-        local START=$1
-        local END=$2
-
-        declare -i timestamp
-        declare -i days
-        declare -i hours
-        declare -i minutes
-        declare -i seconds
-        timestamp=$END-$START
-
-        days=$timestamp/60/60/24
-        hours=$((($timestamp-($days*60*60*24))/60/60))
-        minutes=$((($timestamp-($days*60*60*24)-($hours*60*60))/60))
-        seconds=$((($timestamp-($days*60*60*24)-($hours*60*60)-($minutes*60))))
-        if [ $days -eq 0 ]; then
-        if [ $hours -eq 0 ]; then
-                if [ $minutes -eq 0 ]; then
-                echo "==> Operation took $seconds seconds ..."
-                else
-                echo "==> Operation took $minutes minutes and $seconds seconds ..."
-                fi
-        else
-                echo "==> Operation took $hours hours $minutes minutes and $seconds seconds ..."
-        fi
-        else
-        echo "==> Operation took $days days $hours hours $minutes minutes and $seconds seconds ..."
-        fi
-}
+FREETYPE_VERSION="2.10.2"
+SHA256="e09aa914e4f7a5d723ac381420949c55c0b90b15744adce5d1406046022186ab"
 
 starttimestamp=$(date +%s)
 
-MY_PATH=$(cd `dirname $0` && pwd)
-if [ -z "$MY_PATH" ] ; then
-        # error; for some reason, the path is not accessible
-        # to the script (e.g. permissions re-evaled after suid)
-        echo 'Error: Script path is for some reason not accessible' >&2
-        exit 1  # fail
+MY_PATH=$(cd `dirname ${0}` && pwd)
+if [ -z "${MY_PATH}" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  echo 'Error: Script path is for some reason not accessible' >&2
+  exit 1  # fail
 fi
-cd "$MY_PATH"/../Sources
+cd "${MY_PATH}/../Sources"
 
-if ! [ -x "$(command -v wget)" ]; then
-        echo 'Error: wget is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
-        exit 1
-fi
+source "${MY_PATH}/env"
+source "${MY_PATH}/functions"
 
-# TODO: use libpng from MacCompileStuff
-if ! [ -x "$(command -v libpng16-config)" ]; then
-        echo 'Error: libpng is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
-        exit 1
-fi
+check_wget
+check_xcode
+check_libpng
 
-if xcode-select --install 2>&1 | grep installed; then
-        echo "==> Xcode Command Line Tools are installed..."
-else
-        echo "==> Xcode Command Line Tools aren't installed, installing..."
-        xcode-select --install
-fi
-
-# TODO: Verify checksum
-rm -rf freetype-*
-wget "https://download.savannah.gnu.org/releases/freetype/freetype-$FREETYPE_VERSION.tar.gz"
-tar xf "freetype-$FREETYPE_VERSION.tar.gz"
-rm "freetype-$FREETYPE_VERSION.tar.gz"
-cd "freetype-$FREETYPE_VERSION"
-sh autogen.sh
-./configure --with-harfbuzz=no --enable-shared
-make MACOSX_DEPLOYMENT_TARGET=10.8
-mkdir "freetype-$FREETYPE_VERSION-RELEASE"
-cp "objs/.libs/libfreetype.6.dylib" "freetype-$FREETYPE_VERSION-RELEASE/libfreetype.6.dylib"
-cd "freetype-$FREETYPE_VERSION-RELEASE"
+rm -rf "freetype-"*
+get_src_and_verify_checksum "freetype-${FREETYPE_VERSION}.tar.gz" "${SHA256}" "https://download.savannah.gnu.org/releases/freetype/freetype-${FREETYPE_VERSION}.tar.gz"
+tar xf "${MY_PATH}/../Sources/archives/freetype-${FREETYPE_VERSION}.tar.gz" -C .
+cd "freetype-${FREETYPE_VERSION}"
+./autogen.sh
+./configure --with-harfbuzz=no --with-brotli=no --enable-shared
+make
+mkdir "freetype-${FREETYPE_VERSION}-RELEASE"
+cp "objs/.libs/libfreetype.6.dylib" "freetype-${FREETYPE_VERSION}-RELEASE/libfreetype.6.dylib"
+cd "freetype-${FREETYPE_VERSION}-RELEASE"
 install_name_tool -id "@rpath/libfreetype.6.dylib" "libfreetype.6.dylib"
-edit_dylib_deps libfreetype.6.dylib
-install_name_tool -change "/usr/local/opt/libpng/lib/libpng16.16.dylib" "@loader_path/libpng16.16.dylib" "libfreetype.6.dylib"
-cd "$MY_PATH"/../
-rm -rf CompiledLibs/freetype-*
-mv "Sources/freetype-$FREETYPE_VERSION/freetype-$FREETYPE_VERSION-RELEASE" "CompiledLibs/freetype-$FREETYPE_VERSION-RELEASE"
-rm -rf ../lib/libfreetype.6.dylib
-cp -rf "CompiledLibs/freetype-$FREETYPE_VERSION-RELEASE/libfreetype.6.dylib" "../lib/libfreetype.6.dylib"
+edit_dylib_deps "libfreetype.6.dylib"
+cd "${MY_PATH}/../"
+rm -rf "CompiledLibs/freetype-"*
+mv "Sources/freetype-${FREETYPE_VERSION}/freetype-${FREETYPE_VERSION}-RELEASE" "CompiledLibs/freetype-${FREETYPE_VERSION}-RELEASE"
+rm -rf "../lib/libfreetype.6.dylib"
+cp -rf "CompiledLibs/freetype-${FREETYPE_VERSION}-RELEASE/libfreetype.6.dylib" "../lib/libfreetype.6.dylib"
 echo "==> DONE ..."
 echo
-time_interval_to_string "$starttimestamp" "$(date +%s)"
+time_interval_to_string "${starttimestamp}" "$(date +%s)"
 echo
