Gettext 0.22.5

diff --git a/SourcesAndScripts/Scripts/gettext_build b/SourcesAndScripts/Scripts/gettext_build
--- a/SourcesAndScripts/Scripts/gettext_build
+++ b/SourcesAndScripts/Scripts/gettext_build
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
 #
 # gettext_build
-# Martin Hrubý (hrubymar10), 2018-2023
+# Martin Hrubý (hrubymar10), 2018-2024
 #
 
 set -e
 
-GETTEXT_VERSION="0.22.4"
-SHA256="29217f1816ee2e777fa9a01f9956a14139c0c23cc1b20368f06b2888e8a34116"
+GETTEXT_VERSION="0.22.5"
+SHA256="fe10c37353213d78a5b83d48af231e005c4da84db5ce88037d88355938259640"
 
 starttimestamp=$(date +%s)
 
@@ -24,6 +24,11 @@ source "${MY_PATH}/functions"
 
 check_wget
 check_gsed
+
+if ! is_apple_silicon_mac; then
+  echo "Error: Gettext requires Apple Silicon mac to build universal libs" >&2
+  exit 1
+fi
 
 cd "${SOURCES_PATH}"
 rm -rf "gettext"*
