Gettext 0.20.2 and new scripts usage

diff --git a/SourcesAndScripts/Scripts/gettext_build b/SourcesAndScripts/Scripts/gettext_build
--- a/SourcesAndScripts/Scripts/gettext_build
+++ b/SourcesAndScripts/Scripts/gettext_build
@@ -1,101 +1,50 @@
 #!/usr/bin/env bash
 #
 # gettext_build
-# Martin Hrubý (hrubymar10), 2018-2019
+# Martin Hrubý (hrubymar10), 2018-2020
 #
 
-GETTEXT_VERSION="0.20.1"
+set -e
 
-edit_dylib_deps() {
-        DYLIB=$1
-        DEPS=$(otool -L ${DYLIB} | awk '{print $1;}' | tail -n +2)
-
-        for DEP in $DEPS; do
-                DEP_BASE=$(basename ${DEP})
-                if [ "$DEP_BASE" == "$(basename $DYLIB)" ]; then
-                        continue
-                fi
-                # Is this our redistributable file?
-                if [ -f $(dirname ${DYLIB})/${DEP_BASE} ]; then
-                        install_name_tool -change "${DEP}" "@loader_path/${DEP_BASE}" ${DYLIB}
-                fi
-        done
-}
-
-time_interval_to_string() {
-        local START=$1
-        local END=$2
-
-        declare -i timestamp
-        declare -i days
-        declare -i hours
-        declare -i minutes
-        declare -i seconds
-        timestamp=$END-$START
-
-        days=$timestamp/60/60/24
-        hours=$((($timestamp-($days*60*60*24))/60/60))
-        minutes=$((($timestamp-($days*60*60*24)-($hours*60*60))/60))
-        seconds=$((($timestamp-($days*60*60*24)-($hours*60*60)-($minutes*60))))
-        if [ $days -eq 0 ]; then
-        if [ $hours -eq 0 ]; then
-                if [ $minutes -eq 0 ]; then
-                echo "==> Operation took $seconds seconds ..."
-                else
-                echo "==> Operation took $minutes minutes and $seconds seconds ..."
-                fi
-        else
-                echo "==> Operation took $hours hours $minutes minutes and $seconds seconds ..."
-        fi
-        else
-        echo "==> Operation took $days days $hours hours $minutes minutes and $seconds seconds ..."
-        fi
-}
+GETTEXT_VERSION="0.20.2"
+SHA256="b22b818e644c37f6e3d1643a1943c32c3a9bff726d601e53047d2682019ceaba"
 
 starttimestamp=$(date +%s)
 
-MY_PATH=$(cd `dirname $0` && pwd)
-if [ -z "$MY_PATH" ] ; then
-        # error; for some reason, the path is not accessible
-        # to the script (e.g. permissions re-evaled after suid)
-        echo 'Error: Script path is for some reason not accessible' >&2
-        exit 1  # fail
+MY_PATH=$(cd `dirname ${0}` && pwd)
+if [ -z "${MY_PATH}" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  echo 'Error: Script path is for some reason not accessible' >&2
+  exit 1  # fail
 fi
-cd "$MY_PATH"/../Sources
+cd "${MY_PATH}/../Sources"
 
-if ! [ -x "$(command -v wget)" ]; then
-        echo 'Error: wget is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
-        exit 1
-fi
+source "${MY_PATH}/env"
+source "${MY_PATH}/functions"
 
-if xcode-select --install 2>&1 | grep installed; then
-        echo "==> Xcode Command Line Tools are installed..."
-else
-        echo "==> Xcode Command Line Tools aren't installed, installing..."
-        xcode-select --install
-fi
+check_wget
+check_xcode
 
-# TODO: Verify checksum
-rm -rf gettext-*
-wget "https://ftp.gnu.org/pub/gnu/gettext/gettext-$GETTEXT_VERSION.tar.xz"
-tar xf "gettext-$GETTEXT_VERSION.tar.xz"
-rm "gettext-$GETTEXT_VERSION.tar.xz"
-cd "gettext-$GETTEXT_VERSION"
-./configure --disable-dependency-tracking --enable-shared CXXFLAGS='-stdlib=libc++'
-make MACOSX_DEPLOYMENT_TARGET=10.8
-mkdir "gettext-$GETTEXT_VERSION-RELEASE"
-cp "gettext-runtime/intl/.libs/libintl.8.dylib" "gettext-$GETTEXT_VERSION-RELEASE/libintl.8.dylib"
-cd "gettext-$GETTEXT_VERSION-RELEASE"
+rm -rf "gettext-"*
+get_src_and_verify_checksum "gettext-${GETTEXT_VERSION}.tar.xz" "${SHA256}" "https://ftp.gnu.org/pub/gnu/gettext/gettext-${GETTEXT_VERSION}.tar.xz"
+tar xf "${MY_PATH}/../Sources/archives/gettext-${GETTEXT_VERSION}.tar.xz" -C .
+cd "gettext-${GETTEXT_VERSION}"
+./configure --disable-dependency-tracking --enable-shared
+make
+mkdir "gettext-${GETTEXT_VERSION}-RELEASE"
+cp "gettext-runtime/intl/.libs/libintl.8.dylib" "gettext-${GETTEXT_VERSION}-RELEASE/libintl.8.dylib"
+cd "gettext-${GETTEXT_VERSION}-RELEASE"
 install_name_tool -id "@rpath/libintl.8.dylib" "libintl.8.dylib"
-edit_dylib_deps libintl.8.dylib
-cd "$MY_PATH"/../
-rm -rf CompiledLibs/gettext-*
-mv "Sources/gettext-$GETTEXT_VERSION/gettext-$GETTEXT_VERSION-RELEASE" "CompiledLibs/gettext-$GETTEXT_VERSION-RELEASE"
-rm -rf ../Headers/libintl.h
-cp "Sources/gettext-$GETTEXT_VERSION/gettext-runtime/intl/libintl.h" ../Headers/libintl.h
-rm -rf ../lib/libintl.8.dylib
-cp -rf "CompiledLibs/gettext-$GETTEXT_VERSION-RELEASE/libintl.8.dylib" "../lib/libintl.8.dylib"
+edit_dylib_deps "libintl.8.dylib"
+cd "${MY_PATH}/../"
+rm -rf "CompiledLibs/gettext-"*
+mv "Sources/gettext-${GETTEXT_VERSION}/gettext-${GETTEXT_VERSION}-RELEASE" "CompiledLibs/gettext-${GETTEXT_VERSION}-RELEASE"
+rm -rf "../Headers/libintl.h"
+cp "Sources/gettext-${GETTEXT_VERSION}/gettext-runtime/intl/libintl.h" "../Headers/libintl.h"
+rm -rf "../lib/libintl.8.dylib"
+cp -rf "CompiledLibs/gettext-${GETTEXT_VERSION}-RELEASE/libintl.8.dylib" "../lib/libintl.8.dylib"
 echo "==> DONE ..."
 echo
-time_interval_to_string "$starttimestamp" "$(date +%s)"
+time_interval_to_string "${starttimestamp}" "$(date +%s)"
 echo
