harfbuzz 2.4.0

diff --git a/SourcesAndScripts/Scripts/harfbuzz_build b/SourcesAndScripts/Scripts/harfbuzz_build
--- a/SourcesAndScripts/Scripts/harfbuzz_build
+++ b/SourcesAndScripts/Scripts/harfbuzz_build
@@ -3,8 +3,11 @@
 # harfbuzz_build
 # Martin Hrubý (hrubymar10), 2018-2019
 #
+# libstdc++ is removed from Xcode 10 and higher. You have to use this workaround to
+# build this: https://stackoverflow.com/a/53644801 .
+#
 
-HARFBUZZ_VERSION="2.3.0"
+HARFBUZZ_VERSION="2.4.0"
 
 edit_dylib_deps() {
         DYLIB=$1
@@ -75,6 +78,12 @@ else
         xcode-select --install
 fi
 
+# TODO: use libffi from MacCompileStuff
+if [ ! -f /usr/local/Cellar/libffi/*/lib/libffi.dylib ]; then
+        echo 'Error: libffi is not installed or is not linked. Use Homebrew, install it and force link it. See https://brew.sh/' >&2
+        exit 1
+fi
+
 # TODO: use glib from MacCompileStuff
 if ! [ -x "$(command -v gobject-query)" ]; then
         echo 'Error: glib is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
@@ -105,6 +114,7 @@ wget "https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-$HARFBUZZ_V
 tar xf "harfbuzz-$HARFBUZZ_VERSION.tar.bz2"
 rm "harfbuzz-$HARFBUZZ_VERSION.tar.bz2"
 cd "harfbuzz-$HARFBUZZ_VERSION"
+export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
 ./configure --disable-dependency-tracking --enable-static --with-cairo=yes --with-glib=yes --with-gobject=yes --with-freetype=yes --with-graphite2=yes
 make MACOSX_DEPLOYMENT_TARGET=10.8
 mkdir "harfbuzz-$HARFBUZZ_VERSION-RELEASE"
