libffi 3.3 and new scripts usage

diff --git a/SourcesAndScripts/Scripts/libffi_build b/SourcesAndScripts/Scripts/libffi_build
--- a/SourcesAndScripts/Scripts/libffi_build
+++ b/SourcesAndScripts/Scripts/libffi_build
@@ -1,99 +1,48 @@
 #!/usr/bin/env bash
 #
 # libffi_build
-# Martin Hrubý (hrubymar10), 2018
+# Martin Hrubý (hrubymar10), 2018-2020
 #
 
-LIBFFI_VERSION="3.2.1"
+set -e
 
-edit_dylib_deps() {
-        DYLIB=$1
-        DEPS=$(otool -L ${DYLIB} | awk '{print $1;}' | tail -n +2)
-
-        for DEP in $DEPS; do
-                DEP_BASE=$(basename ${DEP})
-                if [ "$DEP_BASE" == "$(basename $DYLIB)" ]; then
-                        continue
-                fi
-                # Is this our redistributable file?
-                if [ -f $(dirname ${DYLIB})/${DEP_BASE} ]; then
-                        install_name_tool -change "${DEP}" "@loader_path/${DEP_BASE}" ${DYLIB}
-                fi
-        done
-}
-
-time_interval_to_string() {
-        local START=$1
-        local END=$2
-
-        declare -i timestamp
-        declare -i days
-        declare -i hours
-        declare -i minutes
-        declare -i seconds
-        timestamp=$END-$START
-
-        days=$timestamp/60/60/24
-        hours=$((($timestamp-($days*60*60*24))/60/60))
-        minutes=$((($timestamp-($days*60*60*24)-($hours*60*60))/60))
-        seconds=$((($timestamp-($days*60*60*24)-($hours*60*60)-($minutes*60))))
-        if [ $days -eq 0 ]; then
-        if [ $hours -eq 0 ]; then
-                if [ $minutes -eq 0 ]; then
-                echo "==> Operation took $seconds seconds ..."
-                else
-                echo "==> Operation took $minutes minutes and $seconds seconds ..."
-                fi
-        else
-                echo "==> Operation took $hours hours $minutes minutes and $seconds seconds ..."
-        fi
-        else
-        echo "==> Operation took $days days $hours hours $minutes minutes and $seconds seconds ..."
-        fi
-}
+LIBFFI_VERSION="3.3"
+SHA256="72fba7922703ddfa7a028d513ac15a85c8d54c8d67f55fa5a4802885dc652056"
 
 starttimestamp=$(date +%s)
 
-MY_PATH=$(cd `dirname $0` && pwd)
-if [ -z "$MY_PATH" ] ; then
-        # error; for some reason, the path is not accessible
-        # to the script (e.g. permissions re-evaled after suid)
-        echo 'Error: Script path is for some reason not accessible' >&2
-        exit 1  # fail
+MY_PATH=$(cd `dirname ${0}` && pwd)
+if [ -z "${MY_PATH}" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  echo 'Error: Script path is for some reason not accessible' >&2
+  exit 1  # fail
 fi
-cd "$MY_PATH"/../Sources
+cd "${MY_PATH}/../Sources"
 
-if ! [ -x "$(command -v wget)" ]; then
-        echo 'Error: wget is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
-        exit 1
-fi
+source "${MY_PATH}/env"
+source "${MY_PATH}/functions"
 
-if xcode-select --install 2>&1 | grep installed; then
-        echo "==> Xcode Command Line Tools are installed..."
-else
-        echo "==> Xcode Command Line Tools aren't installed, installing..."
-        xcode-select --install
-fi
+check_wget
+check_xcode
 
-# TODO: Verify checksum
-rm -rf libffi-*
-wget "https://sourceware.org/pub/libffi/libffi-$LIBFFI_VERSION.tar.gz"
-tar xf "libffi-$LIBFFI_VERSION.tar.gz"
-rm "libffi-$LIBFFI_VERSION.tar.gz"
-cd "libffi-$LIBFFI_VERSION"
+rm -rf "libffi-"*
+get_src_and_verify_checksum "libffi-${LIBFFI_VERSION}.tar.gz" "${SHA256}" "https://sourceware.org/pub/libffi/libffi-${LIBFFI_VERSION}.tar.gz"
+tar xf "${MY_PATH}/../Sources/archives/libffi-${LIBFFI_VERSION}.tar.gz" -C .
+cd "libffi-${LIBFFI_VERSION}"
 ./configure --disable-dependency-tracking --enable-shared
-make MACOSX_DEPLOYMENT_TARGET=10.8
-mkdir "libffi-$LIBFFI_VERSION-RELEASE"
-cp x86_64-apple-darwin*/".libs/libffi.6.dylib" "libffi-$LIBFFI_VERSION-RELEASE/libffi.6.dylib"
-cd "libffi-$LIBFFI_VERSION-RELEASE"
-install_name_tool -id "@rpath/libffi.6.dylib" "libffi.6.dylib"
-edit_dylib_deps libffi.6.dylib
-cd "$MY_PATH"/../
-rm -rf CompiledLibs/libffi-*
-mv "Sources/libffi-$LIBFFI_VERSION/libffi-$LIBFFI_VERSION-RELEASE" "CompiledLibs/libffi-$LIBFFI_VERSION-RELEASE"
-rm -rf ../lib/libffi.6.dylib
-cp -rf "CompiledLibs/libffi-$LIBFFI_VERSION-RELEASE/libffi.6.dylib" "../lib/libffi.6.dylib"
+make
+mkdir "libffi-${LIBFFI_VERSION}-RELEASE"
+cp "x86_64-apple-darwin"*"/.libs/libffi.7.dylib" "libffi-${LIBFFI_VERSION}-RELEASE/libffi.7.dylib"
+cd "libffi-${LIBFFI_VERSION}-RELEASE"
+install_name_tool -id "@rpath/libffi.7.dylib" "libffi.7.dylib"
+edit_dylib_deps "libffi.7.dylib"
+cd "${MY_PATH}/../"
+rm -rf "CompiledLibs/libffi-"*
+mv "Sources/libffi-${LIBFFI_VERSION}/libffi-${LIBFFI_VERSION}-RELEASE" "CompiledLibs/libffi-${LIBFFI_VERSION}-RELEASE"
+rm -rf "../lib/libffi.7.dylib"
+cp -rf "CompiledLibs/libffi-${LIBFFI_VERSION}-RELEASE/libffi.7.dylib" "../lib/libffi.7.dylib"
 echo "==> DONE ..."
 echo
-time_interval_to_string "$starttimestamp" "$(date +%s)"
+time_interval_to_string "${starttimestamp}" "$(date +%s)"
 echo
