libogg 1.3.4 and new scripts usage

diff --git a/SourcesAndScripts/Scripts/libogg_build b/SourcesAndScripts/Scripts/libogg_build
--- a/SourcesAndScripts/Scripts/libogg_build
+++ b/SourcesAndScripts/Scripts/libogg_build
@@ -1,100 +1,49 @@
 #!/usr/bin/env bash
 #
 # libogg_build
-# Martin Hrubý (hrubymar10), 2019
+# Martin Hrubý (hrubymar10), 2019-2020
 #
 
-LIBOGG_VERSION="1.3.3"
+set -e
 
-edit_dylib_deps() {
-        DYLIB=$1
-        DEPS=$(otool -L ${DYLIB} | awk '{print $1;}' | tail -n +2)
-
-        for DEP in $DEPS; do
-                DEP_BASE=$(basename ${DEP})
-                if [ "$DEP_BASE" == "$(basename $DYLIB)" ]; then
-                        continue
-                fi
-                # Is this our redistributable file?
-                if [ -f $(dirname ${DYLIB})/${DEP_BASE} ]; then
-                        install_name_tool -change "${DEP}" "@loader_path/${DEP_BASE}" ${DYLIB}
-                fi
-        done
-}
-
-time_interval_to_string() {
-        local START=$1
-        local END=$2
-
-        declare -i timestamp
-        declare -i days
-        declare -i hours
-        declare -i minutes
-        declare -i seconds
-        timestamp=$END-$START
-
-        days=$timestamp/60/60/24
-        hours=$((($timestamp-($days*60*60*24))/60/60))
-        minutes=$((($timestamp-($days*60*60*24)-($hours*60*60))/60))
-        seconds=$((($timestamp-($days*60*60*24)-($hours*60*60)-($minutes*60))))
-        if [ $days -eq 0 ]; then
-        if [ $hours -eq 0 ]; then
-                if [ $minutes -eq 0 ]; then
-                echo "==> Operation took $seconds seconds ..."
-                else
-                echo "==> Operation took $minutes minutes and $seconds seconds ..."
-                fi
-        else
-                echo "==> Operation took $hours hours $minutes minutes and $seconds seconds ..."
-        fi
-        else
-        echo "==> Operation took $days days $hours hours $minutes minutes and $seconds seconds ..."
-        fi
-}
+LIBOGG_VERSION="1.3.4"
+SHA256="fe5670640bd49e828d64d2879c31cb4dde9758681bb664f9bdbf159a01b0c76e"
 
 starttimestamp=$(date +%s)
 
-MY_PATH=$(cd `dirname $0` && pwd)
-if [ -z "$MY_PATH" ] ; then
-        # error; for some reason, the path is not accessible
-        # to the script (e.g. permissions re-evaled after suid)
-        echo 'Error: Script path is for some reason not accessible' >&2
-        exit 1  # fail
+MY_PATH=$(cd `dirname ${0}` && pwd)
+if [ -z "${MY_PATH}" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  echo 'Error: Script path is for some reason not accessible' >&2
+  exit 1  # fail
 fi
-cd "$MY_PATH"/../Sources
+cd "${MY_PATH}/../Sources"
 
-if ! [ -x "$(command -v wget)" ]; then
-        echo 'Error: wget is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
-        exit 1
-fi
+source "${MY_PATH}/env"
+source "${MY_PATH}/functions"
 
-if xcode-select --install 2>&1 | grep installed; then
-        echo "==> Xcode Command Line Tools are installed..."
-else
-        echo "==> Xcode Command Line Tools aren't installed, installing..."
-        xcode-select --install
-fi
+check_wget
+check_xcode
 
-# TODO: Verify checksum
-rm -rf libogg-*
-wget "https://downloads.xiph.org/releases/ogg/libogg-$LIBOGG_VERSION.tar.gz"
-tar xf "libogg-$LIBOGG_VERSION.tar.gz"
-rm "libogg-$LIBOGG_VERSION.tar.gz"
-cd "libogg-$LIBOGG_VERSION"
+rm -rf "libogg-"*
+get_src_and_verify_checksum "libogg-${LIBOGG_VERSION}.tar.gz" "${SHA256}" "https://downloads.xiph.org/releases/ogg/libogg-${LIBOGG_VERSION}.tar.gz"
+tar xf "${MY_PATH}/../Sources/archives/libogg-${LIBOGG_VERSION}.tar.gz" -C .
+cd "libogg-${LIBOGG_VERSION}"
 ./configure --disable-dependency-tracking --enable-shared
-make MACOSX_DEPLOYMENT_TARGET=10.8
-mkdir "libogg-$LIBOGG_VERSION-RELEASE"
-cp "src/.libs/libogg.0.dylib" "libogg-$LIBOGG_VERSION-RELEASE/libogg.0.dylib"
-cd "libogg-$LIBOGG_VERSION-RELEASE"
+make
+mkdir "libogg-${LIBOGG_VERSION}-RELEASE"
+cp "src/.libs/libogg.0.dylib" "libogg-${LIBOGG_VERSION}-RELEASE/libogg.0.dylib"
+cd "libogg-${LIBOGG_VERSION}-RELEASE"
 install_name_tool -id "@rpath/libogg.0.dylib" "libogg.0.dylib"
-edit_dylib_deps libogg.0.dylib
-cd "$MY_PATH"/../
-rm -rf CompiledLibs/libogg-*
-mv "Sources/libogg-$LIBOGG_VERSION/libogg-$LIBOGG_VERSION-RELEASE" "CompiledLibs/libogg-$LIBOGG_VERSION-RELEASE"
-rm -rf ../lib/libogg.0.dylib
-cp -rf "CompiledLibs/libogg-$LIBOGG_VERSION-RELEASE/libogg.0.dylib" "../lib/libogg.0.dylib"
-rm -rf ../Headers/ogg
-mkdir ../Headers/ogg
-cp -rf Sources/libogg-$LIBOGG_VERSION/include/ogg/*.h ../Headers/ogg/
+edit_dylib_deps "libogg.0.dylib"
+cd "${MY_PATH}/../"
+rm -rf "CompiledLibs/libogg-"*
+mv "Sources/libogg-${LIBOGG_VERSION}/libogg-${LIBOGG_VERSION}-RELEASE" "CompiledLibs/libogg-${LIBOGG_VERSION}-RELEASE"
+rm -rf "../lib/libogg.0.dylib"
+cp -rf "CompiledLibs/libogg-${LIBOGG_VERSION}-RELEASE/libogg.0.dylib" "../lib/libogg.0.dylib"
+rm -rf "../Headers/ogg"
+mkdir "../Headers/ogg"
+cp -rf "Sources/libogg-${LIBOGG_VERSION}/include/ogg/"*.h "../Headers/ogg/"
 echo "==> DONE ..."
 echo
