libvorbis 1.3.7 and new scripts usage

diff --git a/SourcesAndScripts/Scripts/libvorbis_build b/SourcesAndScripts/Scripts/libvorbis_build
--- a/SourcesAndScripts/Scripts/libvorbis_build
+++ b/SourcesAndScripts/Scripts/libvorbis_build
@@ -1,106 +1,54 @@
 #!/usr/bin/env bash
 #
 # libvorbis_build
-# Martin Hrubý (hrubymar10), 2019
+# Martin Hrubý (hrubymar10), 2019-2020
 #
 
-LIBVORBIS_VERSION="1.3.6"
+set -e
 
-edit_dylib_deps() {
-        DYLIB=$1
-        DEPS=$(otool -L ${DYLIB} | awk '{print $1;}' | tail -n +2)
-
-        for DEP in $DEPS; do
-                DEP_BASE=$(basename ${DEP})
-                if [ "$DEP_BASE" == "$(basename $DYLIB)" ]; then
-                        continue
-                fi
-                # Is this our redistributable file?
-                if [ -f $(dirname ${DYLIB})/${DEP_BASE} ]; then
-                        install_name_tool -change "${DEP}" "@loader_path/${DEP_BASE}" ${DYLIB}
-                fi
-        done
-}
-
-time_interval_to_string() {
-        local START=$1
-        local END=$2
-
-        declare -i timestamp
-        declare -i days
-        declare -i hours
-        declare -i minutes
-        declare -i seconds
-        timestamp=$END-$START
-
-        days=$timestamp/60/60/24
-        hours=$((($timestamp-($days*60*60*24))/60/60))
-        minutes=$((($timestamp-($days*60*60*24)-($hours*60*60))/60))
-        seconds=$((($timestamp-($days*60*60*24)-($hours*60*60)-($minutes*60))))
-        if [ $days -eq 0 ]; then
-        if [ $hours -eq 0 ]; then
-                if [ $minutes -eq 0 ]; then
-                echo "==> Operation took $seconds seconds ..."
-                else
-                echo "==> Operation took $minutes minutes and $seconds seconds ..."
-                fi
-        else
-                echo "==> Operation took $hours hours $minutes minutes and $seconds seconds ..."
-        fi
-        else
-        echo "==> Operation took $days days $hours hours $minutes minutes and $seconds seconds ..."
-        fi
-}
+LIBVORBIS_VERSION="1.3.7"
+SHA256="b33cc4934322bcbf6efcbacf49e3ca01aadbea4114ec9589d1b1e9d20f72954b"
 
 starttimestamp=$(date +%s)
 
-MY_PATH=$(cd `dirname $0` && pwd)
-if [ -z "$MY_PATH" ] ; then
-        # error; for some reason, the path is not accessible
-        # to the script (e.g. permissions re-evaled after suid)
-        echo 'Error: Script path is for some reason not accessible' >&2
-        exit 1  # fail
+MY_PATH=$(cd `dirname ${0}` && pwd)
+if [ -z "${MY_PATH}" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  echo 'Error: Script path is for some reason not accessible' >&2
+  exit 1  # fail
 fi
-cd "$MY_PATH"/../Sources
+cd "${MY_PATH}/../Sources"
 
-if ! [ -x "$(command -v wget)" ]; then
-        echo 'Error: wget is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
-        exit 1
-fi
+source "${MY_PATH}/env"
+source "${MY_PATH}/functions"
 
-if xcode-select --install 2>&1 | grep installed; then
-        echo "==> Xcode Command Line Tools are installed..."
-else
-        echo "==> Xcode Command Line Tools aren't installed, installing..."
-        xcode-select --install
-fi
+check_wget
+check_xcode
+check_libogg
 
-# TODO: Verify checksum
-rm -rf libvorbis-*
-wget "http://downloads.xiph.org/releases/vorbis/libvorbis-$LIBVORBIS_VERSION.tar.xz"
-tar xf "libvorbis-$LIBVORBIS_VERSION.tar.xz"
-rm "libvorbis-$LIBVORBIS_VERSION.tar.xz"
-cd "libvorbis-$LIBVORBIS_VERSION"
+rm -rf "libvorbis-"*
+get_src_and_verify_checksum "libvorbis-${LIBVORBIS_VERSION}.tar.xz" "${SHA256}" "http://downloads.xiph.org/releases/vorbis/libvorbis-${LIBVORBIS_VERSION}.tar.xz"
+tar xf "${MY_PATH}/../Sources/archives/libvorbis-${LIBVORBIS_VERSION}.tar.xz" -C .
+cd "libvorbis-${LIBVORBIS_VERSION}"
 ./configure --disable-dependency-tracking --enable-shared
-make MACOSX_DEPLOYMENT_TARGET=10.8
-mkdir "libvorbis-$LIBVORBIS_VERSION-RELEASE"
-cp "lib/.libs/libvorbis.0.dylib" "libvorbis-$LIBVORBIS_VERSION-RELEASE/libvorbis.0.dylib"
-cp "lib/.libs/libvorbisfile.3.dylib" "libvorbis-$LIBVORBIS_VERSION-RELEASE/libvorbisfile.dylib"
-cd "libvorbis-$LIBVORBIS_VERSION-RELEASE"
+make
+mkdir "libvorbis-${LIBVORBIS_VERSION}-RELEASE"
+cp "lib/.libs/libvorbis.0.dylib" "libvorbis-${LIBVORBIS_VERSION}-RELEASE/libvorbis.0.dylib"
+cp "lib/.libs/libvorbisfile.3.dylib" "libvorbis-${LIBVORBIS_VERSION}-RELEASE/libvorbisfile.dylib"
+cd "libvorbis-${LIBVORBIS_VERSION}-RELEASE"
 install_name_tool -id "@rpath/libvorbis.0.dylib" "libvorbis.0.dylib"
 install_name_tool -id "@rpath/libvorbisfile.dylib" "libvorbisfile.dylib"
-edit_dylib_deps libvorbis.0.dylib
-edit_dylib_deps libvorbisfile.dylib
-install_name_tool -change "/usr/local/opt/libogg/lib/libogg.0.dylib" "@loader_path/libogg.0.dylib" "libvorbis.0.dylib"
-install_name_tool -change "/usr/local/opt/libogg/lib/libogg.0.dylib" "@loader_path/libogg.0.dylib" "libvorbisfile.dylib"
-cd "$MY_PATH"/../
-rm -rf CompiledLibs/libvorbis-*
-mv "Sources/libvorbis-$LIBVORBIS_VERSION/libvorbis-$LIBVORBIS_VERSION-RELEASE" "CompiledLibs/libvorbis-$LIBVORBIS_VERSION-RELEASE"
-rm -rf ../lib/libvorbis*
-cp -rf "CompiledLibs/libvorbis-$LIBVORBIS_VERSION-RELEASE/libvorbis.0.dylib" "../lib/libvorbis.0.dylib"
-cp -rf "CompiledLibs/libvorbis-$LIBVORBIS_VERSION-RELEASE/libvorbisfile.dylib" "../lib/libvorbisfile.dylib"
-rm -rf ../Headers/vorbis
-mkdir ../Headers/vorbis
-cp -rf Sources/libvorbis-$LIBVORBIS_VERSION/include/vorbis/*.h ../Headers/vorbis/
+edit_dylib_deps "libvorbis.0.dylib"
+edit_dylib_deps "libvorbisfile.dylib"
+cd "${MY_PATH}"/../
+rm -rf "CompiledLibs/libvorbis-"*
+mv "Sources/libvorbis-${LIBVORBIS_VERSION}/libvorbis-${LIBVORBIS_VERSION}-RELEASE" "CompiledLibs/libvorbis-${LIBVORBIS_VERSION}-RELEASE"
+rm -rf "../lib/libvorbis"*
+cp -rf "CompiledLibs/libvorbis-${LIBVORBIS_VERSION}-RELEASE/libvorbis.0.dylib" "../lib/libvorbis.0.dylib"
+cp -rf "CompiledLibs/libvorbis-${LIBVORBIS_VERSION}-RELEASE/libvorbisfile.dylib" "../lib/libvorbisfile.dylib"
+rm -rf "../Headers/vorbis"
+mkdir "../Headers/vorbis"
+cp -rf "Sources/libvorbis-${LIBVORBIS_VERSION}/include/vorbis/"*.h "../Headers/vorbis/"
 echo "==> DONE ..."
 echo
