Build in order by dependence

diff --git a/SourcesAndScripts/Build_All b/SourcesAndScripts/Build_All
--- a/SourcesAndScripts/Build_All
+++ b/SourcesAndScripts/Build_All
@@ -1,56 +1,51 @@
 #!/usr/bin/env bash
 #
 # Build_All
-# Martin Hrubý (hrubymar10), 2018
+# Martin Hrubý (hrubymar10), 2018-2020
 #
 
-time_interval_to_string() {
-        local START=$1
-        local END=$2
-
-        declare -i timestamp
-        declare -i days
-        declare -i hours
-        declare -i minutes
-        declare -i seconds
-        timestamp=$END-$START
-
-        days=$timestamp/60/60/24
-        hours=$((($timestamp-($days*60*60*24))/60/60))
-        minutes=$((($timestamp-($days*60*60*24)-($hours*60*60))/60))
-        seconds=$((($timestamp-($days*60*60*24)-($hours*60*60)-($minutes*60))))
-        if [ $days -eq 0 ]; then
-        if [ $hours -eq 0 ]; then
-                if [ $minutes -eq 0 ]; then
-                echo "==> Operation took $seconds seconds ..."
-                else
-                echo "==> Operation took $minutes minutes and $seconds seconds ..."
-                fi
-        else
-                echo "==> Operation took $hours hours $minutes minutes and $seconds seconds ..."
-        fi
-        else
-        echo "==> Operation took $days days $hours hours $minutes minutes and $seconds seconds ..."
-        fi
-}
+set -e
 
 starttimestamp=$(date +%s)
 
-MY_PATH=$(cd `dirname $0` && pwd)
-if [ -z "$MY_PATH" ] ; then
-        # error; for some reason, the path is not accessible
-        # to the script (e.g. permissions re-evaled after suid)
-        echo 'Error: Script path is for some reason not accessible' >&2
-        exit 1  # fail
+MY_PATH=$(cd `dirname ${0}` && pwd)
+if [ -z "${MY_PATH}" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  echo 'Error: Script path is for some reason not accessible' >&2
+  exit 1  # fail
 fi
-cd "$MY_PATH"/Scripts
+cd "${MY_PATH}/Scripts"
 
-for filename in * ; do
-        echo "==> Running $filename"
-        ./"$filename"
+source "${MY_PATH}/Scripts/functions"
+
+SCRIPTS=(
+  "fribidi"
+  "libogg"
+  "libvorbis"
+  "libffi"
+  "libpng"
+  "freetype"
+  "SDL2"
+  "gettext"
+  "pixman"
+  "fontconfig"
+  "graphite2"
+  "readline"
+  "pcre"
+  "boost"
+  "glib"
+  "cairo"
+  "harfbuzz"
+  "pango"
+)
+
+for SCRIPT in "${SCRIPTS[@]}"; do
+  echo "==> Building ${SCRIPT}"
+  ./"${SCRIPT}_build"
 done
 
 echo "==> DONE ..."
 echo
-time_interval_to_string "$starttimestamp" "$(date +%s)"
+time_interval_to_string "${starttimestamp}" "$(date +%s)"
 echo
